### ISSUE TITLE
Can NIEP be used for virtualising fuctionality like load balancing, firewall for a SDN network?

### ISSUE THREAD

**Issue by burhanqayoom** [ViniGarcia/NIEP#1]

**Comment by ViniGarcia** [comment]
Currently, you can not deploy the network functions in an SDN network. It is not possible to control the VNFs' interfaces with the OpenFlow protocol. Actually, in the current version, the VNFs are directly connected with Linux bridges. However, although you can not use SDN to control the service chain, it can be employed to control mininet virtual switches with no problems.

**Comment by burhanqayoom** [comment]
I do not understand. I don't have such knowledge. I know SDN working in mininet well, but how can a fuctionality like load balancing be used for SDN as an VNF? Is it to be deployed on some VM or in a mininet host? How the functionality would be connected to the SDN network? Is there a need to change the controller code to match with the functionality?

**Comment by lmarcuzzo** [comment]
In NIEP, each VNF runs as a separate VM which is connected to the Mininet topology via static links (through Linux Bridged). To run a function, such as a firewall, on a VNF connected to the Mininet topology, you need to configure the links in a way in which traffic passes through the VNF, such as S1(mininet) -> VNF(VM) -> S2(mininet).
In this case, the only way to S1 and S2 communicate is via the VNF, which can then act as a firewall. However, these links are static, and while you can still interact with both switches via OpenFlow, you cannot configure the links to the VNF.

As for the Load Balancer, a VNF also can also be an SDN controller, such as ONOS. This way, you can connect the VNF as an external controller to the Mininet topology, although we do not support this case yet.
